import os
API_ID = int(os.environ.get("API_ID",29109422 ))
API_HASH = os.environ.get("API_HASH", None) 
BOT_TOKEN = os.environ.get("BOT_TOKEN", None) 
openai.api_key = os.environ.get("sk-proj-gQIV34ntzlfyZQg2Zn5IT3BlbkFJpTTSVGMnbEYYjssPUaCc")
BOT_USERNAME = os.environ.get("BOT_USERNAME" ,None) 
SUDO=os.environ.get("SUDO","7080052423")
BOT_NAME = os.environ.get("naxx",None)
START_IMG = os.environ.get("START_IMG","https://telegra.ph/file/4b1d7157f8b50a346728b.jpg")
STKR = os.environ.get("STKR","CAACAgEAAx0CRjAUHgABAsULZASkFZUsTQTw2k-FvC2SBJnd-vAAAokCAALW9iBFzemsQBDIqWkuBA")
BANNED_USERS=os.environ.get("BANNED_USERS",None)
UPDATE_CHNL = os.environ.get("https://t.me/radhe_shyam_ji",None)
OWNER_USERNAME = os.environ.get("btwnaksh")
SUDO=os.environ.get("SUDO","7080052423")
SUPPORT_GRP = os.environ.get("SUPPORT_GROUP","https://t.me/PAPANAKSH")
BARD_TOKEN=os.environ.get("BARD_TOKEN","")
